/* eslint-disable prettier/prettier */
export default {
  "absolute": "Sets an elements position",
  "accessibility": "Controls whether an element is visually hidden but still accessible to screen readers",
  "align": "Sets an elements vertical alignment",
  "align-content": "Controls how lines are positioned in multi-line flex containers",
  "align-items": "Sets flex items position along a contrainer's cross axis.",
  "align-self": "Controls how an individual flex item is positioned along container's cross axis.",
  "align-text": "Sets the vertical alignment of an inline or table-cell box",
  "animate": "Sets CSS animations",
  "antialiased": "Sets the antialiasing of the font",
  "appearance": "Disables native styling based on the operating system's theme.",
  "auto-cols": "Controls the size of auto-generated (implicit) grid columns",
  "auto-rows": "Controls the size of auto-generated (implicit) grid rows",
  "background-attachment": "Sets behavior of background images when scrolling",
  "background-position": "Sets position of a background image",
  "background-repeat": "Sets repetition of a background image",
  "bg": "Sets background color or size of a background image",
  "bg-gradient": "Sets background image",
  "block": "Sets the display box type of an element",
  "border": "Sets color for border or Sets width for borders in increments of 1px",
  "border-collapse": "Collapse or separate table borders",
  "border-style": "Sets style for borders",
  "bottom": "Sets the placement of a positioned element",
  "box": "Sets how the total width and height of an element is calculated",
  "box-sizing": "Sets how the total width and height of an element is calculated",
  "break": "Sets the word breaks of an element",
  "capitalize": "Sets the capitalization of text",
  "clear": "Sets whether an element is moved below preceding floated elements",
  "col": "Sets a grid item size and location within the grid column",
  "col-end": "Sets a grid item size and location within the grid column",
  "col-span": "Sets a grid item size and location within the grid column",
  "col-start": "Sets a grid item size and location within the grid column",
  "container": "Sets the max-width to match the min-width of the current breakpoint",
  "content": "Controls how lines are positioned in multi-line flex containers",
  "contents": "Sets the display box type of an element",
  "cursor": "Changes the cursor when hovering over an element",
  "cursor-not": "Changes the cursor when hovering over an element",
  "delay": "Sets the delay for transitions",
  "diagonal": "Sets the font number variant",
  "display": "Sets element to be a flex container",
  "divide": "Sets divide color or width",
  "duration": "Sets the length of time for a transition animations to complete",
  "ease": "Sets the easing function of transition animations",
  "ease-in": "Sets the easing function of transition animations",
  "fill": "Set SVG fill style",
  "fixed": "Sets an elements position",
  "flex": "Controls how flex items grow and shrink",
  "flex-col": "Sets direction of flex items",
  "flex-direction": "Sets direction of flex items",
  "flex-grow": "Controls how flex items grow",
  "flex-row": "Sets direction of flex items",
  "flex-shrink": "Controls how flex items shrink",
  "flex-wrap": "Creates how flex items wrap",
  "float": "Sets an element's placement to a side of its container and allows content to wrap around it.",
  "flow": "Sets the display box type of an element",
  "font": "Sets the font weight",
  "font-family": "Sets the font family",
  "font-smoothing": "Sets the smoothing for font",
  "font-style": "Sets style of the font",
  "from": "Sets the background color gradients and where to stop",
  "gap": "Sets the gaps (gutters) between rows and columns",
  "gap-x": "Sets the gaps (gutters) between rows and columns",
  "gap-y": "Sets the gaps (gutters) between rows and columns",
  "grid": "Sets the display box type of an element",
  "grid-auto-flow": "Controls the auto placement of grid elements",
  "grid-cols": "Defines columns for grid layout",
  "grid-column": "Sets a grid item size and location within the grid column",
  "grid-flow": "Controls the auto placement of grid elements",
  "grid-flow-col": "Controls the auto placement of grid elements",
  "grid-flow-row": "Controls the auto placement of grid elements",
  "grid-row": "Sets a grid item size and location within the grid row",
  "grid-rows": "Defines rows for grid layout",
  "grid-tempate-columns": "Defines columns for grid layout",
  "grid-temptale-rows": "Defines rows for grid layout",
  "h": "Sets height of an element",
  "hidden": "visibility: hidden",
  "inline": "Sets the display box type of an element or Sets element to be a flex container",
  "inset": "Sets the placement of a positioned element",
  "invisible": "Show or hide without affecting the layout of the document",
  "italic": "Sets the style of the font",
  "items": "Sets flex items position along a contrainers cross axis",
  "justify": "Controls how flex items are positioned along containers main axis",
  "justify-content": "Controls how flex items are positioned along container's main axis.",
  "justify-items": "Controls how flex items are positioned along containers main axis",
  "justify-self": "Controls how flex items are positioned along containers main axis",
  "leading": "Sets the line height",
  "left": "Sets the placement of a positioned element",
  "line": "Sets the text-decoration of an element",
  "lining": "Sets the font number variant",
  "list": "Sets the bullet style of a list",
  "list-style-position": "Sets the position of a list's bullets.",
  "list-style-type": "Sets the bullet style of a list",
  "lowercase": "Sets the capitalization of text",
  "m": "Controls margin (and negative margin) in 0.25rem increments",
  "max-h": "Sets the maxiumum height of an element",
  "max-w": "Sets the maxiumum width of an element",
  "max-w-screen": "Sets the maxiumum width of an element",
  "mb": "Controls margin (and negative margin) in 0.25rem increments",
  "min-h": "Sets the minimum height of an element",
  "min-w": "Sets the minimum width of an element",
  "ml": "Controls margin (and negative margin) in 0.25rem increments",
  "mr": "Controls margin (and negative margin) in 0.25rem increments",
  "mt": "Controls margin (and negative margin) in 0.25rem increments",
  "mx": "Controls margin (and negative margin) in 0.25rem increments",
  "my": "Controls margin (and negative margin) in 0.25rem increments",
  "no-underline": "Sets the text-decoration of an element",
  "normal-case": "Sets the capitalization of text",
  "normal-nums": "Sets the font number variant",
  "not-italic": "Sets the style of the font",
  "not-sr-only": "Controls whether an element is visually hidden but still accessible to screen readers",
  "object": "Sets how the content of a replaced element (img or video tag) should be resized (contain, cover, fill, none, scale-down) OR Sets the alignment of the selected replaced element (bottom, center, left etc.)",
  "object-fit": "Sets how the content of a replaced element (img or video tag) should be resized",
  "object-position": "Sets the alignment of the selected replaced element",
  "oldstyle-nums": "Sets the font number variant",
  "opacity": "Sets opacity of an element",
  "order": "Controls how flex items are ordered",
  "ordinal": "Sets the font number variant",
  "origin": "Sets the origin of an element transforms. Think of the origin as pushing a thumbtack into the element at the specified position",
  "outline": "Changes outline of an element",
  "overflow": "Sets how to handle content that's too big for its container.",
  "overflow-x": "Sets how to handle content that's too big for its container.",
  "overflow-y": "Sets how to handle content that's too big for its container.",
  "overscroll": "Sets browser behavior upon reaching the boundary of a scrolling area",
  "p": "Controls padding in 0.25rem increments",
  "pb": "Controls padding in 0.25rem increments",
  "pl": "Controls padding in 0.25rem increments",
  "place-content": "Controls alignment in both directions at once for grid or flexbox",
  "place-items": "Controls alignment of items in both directions at once for grid or flexbox",
  "place-self": "Controls alignment of individual element in both directions at once for grid or flexbox",
  "placeholder": "Sets the placeholder color using the ::placeholder pseudo element",
  "pointer-events": "Specifies whether an element is the target of mouse events",
  "position": "Sets an element's position.",
  "pr": "Controls padding in 0.25rem increments",
  "proportional-nums": "Sets the font number variant",
  "pt": "Controls padding in 0.25rem increments",
  "px": "Controls padding in 0.25rem increments",
  "py": "Controls padding in 0.25rem increments",
  "relative": "Sets an element position to relative",
  "resize": "Sets whether an element is resizable, along with direction",
  "right": "Sets the placement of a positioned element",
  "ring": "Sets the width of outline rings using box shadows",
  "ring-offset": "Sets an offset for outline rings (0,1,2, etc) OR sets the color of the outline ring offset",
  "rotate": "Rotates an element that has transform applied",
  "rounded": "Sets border radius",
  "row": "Sets a grid item size and location within the grid row",
  "scale": "Scales an element that has transform applied",
  "scale-x": "Scales an element that has transform applied",
  "scale-y": "Scales an element that has transform applied",
  "select": "Controls whether the user can select text",
  "self": "Controls how an individual flex item is positioned along containers cross axis",
  "shadow": "Sets shadow of an element",
  "skew": "Skews an element that has transform applied",
  "slashed-zero": "Sets the font number variant",
  "space": "Sets left or top (x or y) margin between child elements, but skips the first element",
  "sr-only": "Controls whether an element is visually hidden but still accessible to screen readers",
  "stacked-fractions": "Sets the font number variant",
  "static": "Sets an element position",
  "sticky": "Sets an element position",
  "stroke": "Set SVG stroke style",
  "stroke-width": "Set SVG stroke width",
  "subpixel-antialiased": "Sets the antialiasing of the font",
  "table": "Sets the display box type of an element",
  "table-layout": "Defines the algorithm used to lay out table cells, rows, and columns",
  "tabular-nums": "Sets the font number variant",
  "text": "Sets the text color or size",
  "text-align": "Sets the alignment of text",
  "text-decoration": "Sets the decoration of the text",
  "text-transform": "Sets the transform attributes of the text",
  "to": "Sets the background color gradients and where to stop",
  "top": "Sets the placement of a positioned element",
  "tracking": "Sets the spacing between letters",
  "transform": "Sets the transform of an element",
  "transform-origin": "Sets the origin of an element's transforms. Think of the origin as pushing a thumbtack into the element at the specified position.",
  "transition": "Sets the CSS properties affected by transition animations",
  "transition-delay": "Sets the length of time for a transition delay",
  "transition-duration": "Sets the length of time for a transition animations to complete",
  "transition-property": "Sets the CSS properties affected by transition animations",
  "transition-timing-function": "Sets the easing function of transition animations",
  "translate": "Translates an element that has transform applied",
  "truncate": "Sets the overflow of text and sets the word breaks of an element",
  "underline": "Sets the text-decoration of an element",
  "uppercase": "Sets the capitalization of text",
  "user-select": "Controls whether the user can select text",
  "vertical-align": "Sets the vertical alignment of an inline or table-cell box",
  "via": "Sets the background color gradients and where to stop",
  "visibility": "visibility: visible",
  "visible": "Sets how to handle content thats too big for its container",
  "w": "Sets width of an element",
  "white-space": "Sets the whitespace of an element",
  "whitespace": "Sets the whitespace of an element",
  "whitespace-pre": "Sets the whitespace of an element",
  "word-break": "Sets the word breaks of an element",
  "z": "Sets the z-order (stack order) of a positioned element"
}

export const VARIANTS = {
  "tw": "Set styles using Tailwind CSS",
  "sm": "Set styles used for small screens and up",
  "md": "Set styles used for medium screens and up",
  "lg": "Set styles used for large screens and up",
  "xl": "Set styles used for extra large screens and up",
  "2xl": "Set styles used for largest screens and up",
  "dark": "Set styles used in dark mode",
  "motion-safe": "Apply styles when the prefers-reduced-motion media feature matches 'no-preference'",
  "motion-reduce": "Apply styles when the prefers-reduced-motion media feature matches 'reduce'",
  "group-hover": "Apply styles to a child element when hovering over a specific parent element",
  "group-focus": "Apply styles to a child element when pecific parent element has focus",
  "hover": "Apply styles to an element when hovering over the element",
  "focus-within": "Apply styles to a parent element when focus is within a child element",
  "focus-visible": "Apply styles to a parent element when focus is within a child element and user is using the keyboard",
  "focus": "Apply styles to an element when element is focused",
  "active": "Apply styles to an element when element is active",
  "visited": "Apply styles to a link element when link has been visited",
  "disabled": "Apply styles to an element when element is diasabled",
  "checked": "Apply styles to an checkbox element when element is checked",
  "first": "Apply styles to a child element when it is the first-child of its parent",
  "last": "Apply styles to a child element when it is the last-child of its parent",
  "odd": "Apply styles to a child element when it is an odd-child of its parent",
  "even": "Apply styles to a child element when it is an even-child of its parent"
}